/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

const metadata = {
    models: {
        user: {
            name: 'User', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, email: {
                    name: "email",
                    type: "String",
                }, password: {
                    name: "password",
                    type: "String",
                }, username: {
                    name: "username",
                    type: "String",
                }, accountType: {
                    name: "accountType",
                    type: "AccountType",
                    attributes: [{ "name": "@default", "args": [] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, transactions: {
                    name: "transactions",
                    type: "Transaction",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, budgetPreference: {
                    name: "budgetPreference",
                    type: "UserBudgetPreference",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'user',
                }, monthlyBudgets: {
                    name: "monthlyBudgets",
                    type: "MonthlyIncomeBudget",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                }, savingGoals: {
                    name: "savingGoals",
                    type: "SavingGoal",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'user',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, email: {
                    name: "email",
                    fields: ["email"]
                }, username: {
                    name: "username",
                    fields: ["username"]
                },
            }
            ,
        }
        ,
        transaction: {
            name: 'Transaction', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'transactions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, amount: {
                    name: "amount",
                    type: "Float",
                }, type: {
                    name: "type",
                    type: "TransactionType",
                }, category: {
                    name: "category",
                    type: "Category",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'transactions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "categoryId" },
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'category',
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, source: {
                    name: "source",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, date: {
                    name: "date",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, savingGoal: {
                    name: "savingGoal",
                    type: "SavingGoal",
                    isDataModel: true,
                    isOptional: true,
                    backLink: 'transactions',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "savingGoalId" },
                }, savingGoalId: {
                    name: "savingGoalId",
                    type: "String",
                    isOptional: true,
                    isForeignKey: true,
                    relationField: 'savingGoal',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
        category: {
            name: 'Category', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, name: {
                    name: "name",
                    type: "String",
                }, budgetType: {
                    name: "budgetType",
                    type: "BudgetType",
                }, description: {
                    name: "description",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }, { "name": "@default", "args": [] }],
                }, transactions: {
                    name: "transactions",
                    type: "Transaction",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                }, savingGoals: {
                    name: "savingGoals",
                    type: "SavingGoal",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'category',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, name: {
                    name: "name",
                    fields: ["name"]
                },
            }
            ,
        }
        ,
        userBudgetPreference: {
            name: 'UserBudgetPreference', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'budgetPreference',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, strategy: {
                    name: "strategy",
                    type: "BudgetAllocationStrategy",
                    attributes: [{ "name": "@default", "args": [] }],
                }, needsPercentage: {
                    name: "needsPercentage",
                    type: "Float",
                    attributes: [{ "name": "@default", "args": [{ "value": 50 }] }],
                }, wantsPercentage: {
                    name: "wantsPercentage",
                    type: "Float",
                    attributes: [{ "name": "@default", "args": [{ "value": 30 }] }],
                }, savingsPercentage: {
                    name: "savingsPercentage",
                    type: "Float",
                    attributes: [{ "name": "@default", "args": [{ "value": 20 }] }],
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId: {
                    name: "userId",
                    fields: ["userId"]
                },
            }
            ,
        }
        ,
        monthlyIncomeBudget: {
            name: 'MonthlyIncomeBudget', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'monthlyBudgets',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, monthYear: {
                    name: "monthYear",
                    type: "DateTime",
                }, totalIncome: {
                    name: "totalIncome",
                    type: "Float",
                }, needsBudget: {
                    name: "needsBudget",
                    type: "Float",
                }, wantsBudget: {
                    name: "wantsBudget",
                    type: "Float",
                }, savingsBudget: {
                    name: "savingsBudget",
                    type: "Float",
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                }, userId_monthYear: {
                    name: "userId_monthYear",
                    fields: ["userId", "monthYear"]
                },
            }
            ,
        }
        ,
        savingGoal: {
            name: 'SavingGoal', fields: {
                id: {
                    name: "id",
                    type: "String",
                    isId: true,
                    attributes: [{ "name": "@default", "args": [] }],
                }, user: {
                    name: "user",
                    type: "User",
                    isDataModel: true,
                    backLink: 'savingGoals',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "userId" },
                }, userId: {
                    name: "userId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'user',
                }, name: {
                    name: "name",
                    type: "String",
                }, targetAmount: {
                    name: "targetAmount",
                    type: "Float",
                }, currentAmount: {
                    name: "currentAmount",
                    type: "Float",
                    attributes: [{ "name": "@default", "args": [{ "value": 0 }] }],
                }, deadline: {
                    name: "deadline",
                    type: "DateTime",
                    isOptional: true,
                }, category: {
                    name: "category",
                    type: "Category",
                    isDataModel: true,
                    backLink: 'savingGoals',
                    isRelationOwner: true,
                    foreignKeyMapping: { "id": "categoryId" },
                }, categoryId: {
                    name: "categoryId",
                    type: "String",
                    isForeignKey: true,
                    relationField: 'category',
                }, note: {
                    name: "note",
                    type: "String",
                    isOptional: true,
                }, createdAt: {
                    name: "createdAt",
                    type: "DateTime",
                    attributes: [{ "name": "@default", "args": [] }],
                }, updatedAt: {
                    name: "updatedAt",
                    type: "DateTime",
                    attributes: [{ "name": "@updatedAt", "args": [] }],
                }, transactions: {
                    name: "transactions",
                    type: "Transaction",
                    isDataModel: true,
                    isArray: true,
                    backLink: 'savingGoal',
                },
            }
            , uniqueConstraints: {
                id: {
                    name: "id",
                    fields: ["id"]
                },
            }
            ,
        }
        ,
    }
    ,
    deleteCascade: {
        user: ['Transaction', 'UserBudgetPreference', 'MonthlyIncomeBudget', 'SavingGoal'],
    }
    ,
    authModel: 'User'
};
export default metadata;
