/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, MonthlyIncomeBudget } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateMonthlyIncomeBudget(options?: Omit<(UseMutationOptions<(MonthlyIncomeBudget | undefined), DefaultError, Prisma.MonthlyIncomeBudgetCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MonthlyIncomeBudgetCreateArgs, DefaultError, MonthlyIncomeBudget, true>('MonthlyIncomeBudget', 'POST', `${endpoint}/monthlyIncomeBudget/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MonthlyIncomeBudgetCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MonthlyIncomeBudget, Prisma.MonthlyIncomeBudgetGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MonthlyIncomeBudget, Prisma.MonthlyIncomeBudgetGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyMonthlyIncomeBudget(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MonthlyIncomeBudgetCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MonthlyIncomeBudgetCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('MonthlyIncomeBudget', 'POST', `${endpoint}/monthlyIncomeBudget/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MonthlyIncomeBudgetCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetFindManyArgs, TQueryFnData = Array<Prisma.MonthlyIncomeBudgetGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/findMany`, args, options, fetch);
}

export function useInfiniteFindManyMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetFindManyArgs, TQueryFnData = Array<Prisma.MonthlyIncomeBudgetGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/findMany`, args, options, fetch);
}

export function useSuspenseFindManyMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetFindManyArgs, TQueryFnData = Array<Prisma.MonthlyIncomeBudgetGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetFindManyArgs, TQueryFnData = Array<Prisma.MonthlyIncomeBudgetGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/findMany`, args, options, fetch);
}

export function useFindUniqueMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetFindUniqueArgs, TQueryFnData = Prisma.MonthlyIncomeBudgetGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetFindUniqueArgs, TQueryFnData = Prisma.MonthlyIncomeBudgetGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/findUnique`, args, options, fetch);
}

export function useFindFirstMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetFindFirstArgs, TQueryFnData = Prisma.MonthlyIncomeBudgetGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetFindFirstArgs, TQueryFnData = Prisma.MonthlyIncomeBudgetGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/findFirst`, args, options, fetch);
}

export function useUpdateMonthlyIncomeBudget(options?: Omit<(UseMutationOptions<(MonthlyIncomeBudget | undefined), DefaultError, Prisma.MonthlyIncomeBudgetUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MonthlyIncomeBudgetUpdateArgs, DefaultError, MonthlyIncomeBudget, true>('MonthlyIncomeBudget', 'PUT', `${endpoint}/monthlyIncomeBudget/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MonthlyIncomeBudgetUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MonthlyIncomeBudget, Prisma.MonthlyIncomeBudgetGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MonthlyIncomeBudget, Prisma.MonthlyIncomeBudgetGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyMonthlyIncomeBudget(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MonthlyIncomeBudgetUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MonthlyIncomeBudgetUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('MonthlyIncomeBudget', 'PUT', `${endpoint}/monthlyIncomeBudget/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MonthlyIncomeBudgetUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertMonthlyIncomeBudget(options?: Omit<(UseMutationOptions<(MonthlyIncomeBudget | undefined), DefaultError, Prisma.MonthlyIncomeBudgetUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MonthlyIncomeBudgetUpsertArgs, DefaultError, MonthlyIncomeBudget, true>('MonthlyIncomeBudget', 'POST', `${endpoint}/monthlyIncomeBudget/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MonthlyIncomeBudgetUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MonthlyIncomeBudget, Prisma.MonthlyIncomeBudgetGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MonthlyIncomeBudget, Prisma.MonthlyIncomeBudgetGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteMonthlyIncomeBudget(options?: Omit<(UseMutationOptions<(MonthlyIncomeBudget | undefined), DefaultError, Prisma.MonthlyIncomeBudgetDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MonthlyIncomeBudgetDeleteArgs, DefaultError, MonthlyIncomeBudget, true>('MonthlyIncomeBudget', 'DELETE', `${endpoint}/monthlyIncomeBudget/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MonthlyIncomeBudgetDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, MonthlyIncomeBudget, Prisma.MonthlyIncomeBudgetGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, MonthlyIncomeBudget, Prisma.MonthlyIncomeBudgetGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyMonthlyIncomeBudget(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.MonthlyIncomeBudgetDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.MonthlyIncomeBudgetDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('MonthlyIncomeBudget', 'DELETE', `${endpoint}/monthlyIncomeBudget/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.MonthlyIncomeBudgetDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.MonthlyIncomeBudgetDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetAggregateArgs, TQueryFnData = Prisma.GetMonthlyIncomeBudgetAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetAggregateArgs, TQueryFnData = Prisma.GetMonthlyIncomeBudgetAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/aggregate`, args, options, fetch);
}

export function useGroupByMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.MonthlyIncomeBudgetGroupByArgs['orderBy'] } : { orderBy?: Prisma.MonthlyIncomeBudgetGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.MonthlyIncomeBudgetGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.MonthlyIncomeBudgetGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.MonthlyIncomeBudgetGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.MonthlyIncomeBudgetGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.MonthlyIncomeBudgetGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.MonthlyIncomeBudgetGroupByArgs['orderBy'] } : { orderBy?: Prisma.MonthlyIncomeBudgetGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.MonthlyIncomeBudgetGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.MonthlyIncomeBudgetGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.MonthlyIncomeBudgetGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.MonthlyIncomeBudgetGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.MonthlyIncomeBudgetGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/groupBy`, args, options, fetch);
}

export function useCountMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.MonthlyIncomeBudgetCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/count`, args, options, fetch);
}

export function useSuspenseCountMonthlyIncomeBudget<TArgs extends Prisma.MonthlyIncomeBudgetCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.MonthlyIncomeBudgetCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.MonthlyIncomeBudgetCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/count`, args, options, fetch);
}

export function useCheckMonthlyIncomeBudget<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; userId?: string }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('MonthlyIncomeBudget', `${endpoint}/monthlyIncomeBudget/check`, args, options, fetch);
}
