/******************************************************************************
* This file was generated by ZenStack CLI.
******************************************************************************/

/* eslint-disable */
// @ts-nocheck

import type { Prisma, UserBudgetPreference } from "@prisma/client";
import type { UseMutationOptions, UseQueryOptions, UseInfiniteQueryOptions, InfiniteData } from '@tanstack/react-query';
import { getHooksContext } from '@zenstackhq/tanstack-query/runtime-v5/react';
import { useModelQuery, useInfiniteModelQuery, useModelMutation } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { PickEnumerable, CheckSelect, QueryError, ExtraQueryOptions, ExtraMutationOptions } from '@zenstackhq/tanstack-query/runtime-v5';
import type { PolicyCrudKind } from '@zenstackhq/runtime'
import metadata from './__model_meta';
type DefaultError = QueryError;
import { useSuspenseModelQuery, useSuspenseInfiniteModelQuery } from '@zenstackhq/tanstack-query/runtime-v5/react';
import type { UseSuspenseQueryOptions, UseSuspenseInfiniteQueryOptions } from '@tanstack/react-query';

export function useCreateUserBudgetPreference(options?: Omit<(UseMutationOptions<(UserBudgetPreference | undefined), DefaultError, Prisma.UserBudgetPreferenceCreateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserBudgetPreferenceCreateArgs, DefaultError, UserBudgetPreference, true>('UserBudgetPreference', 'POST', `${endpoint}/userBudgetPreference/create`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserBudgetPreferenceCreateArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceCreateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, UserBudgetPreference, Prisma.UserBudgetPreferenceGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceCreateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, UserBudgetPreference, Prisma.UserBudgetPreferenceGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useCreateManyUserBudgetPreference(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.UserBudgetPreferenceCreateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserBudgetPreferenceCreateManyArgs, DefaultError, Prisma.BatchPayload, false>('UserBudgetPreference', 'POST', `${endpoint}/userBudgetPreference/createMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserBudgetPreferenceCreateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceCreateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceCreateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useFindManyUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceFindManyArgs, TQueryFnData = Array<Prisma.UserBudgetPreferenceGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceFindManyArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/findMany`, args, options, fetch);
}

export function useInfiniteFindManyUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceFindManyArgs, TQueryFnData = Array<Prisma.UserBudgetPreferenceGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceFindManyArgs>, options?: Omit<UseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useInfiniteModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/findMany`, args, options, fetch);
}

export function useSuspenseFindManyUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceFindManyArgs, TQueryFnData = Array<Prisma.UserBudgetPreferenceGetPayload<TArgs> & { $optimistic?: boolean }>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceFindManyArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/findMany`, args, options, fetch);
}

export function useSuspenseInfiniteFindManyUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceFindManyArgs, TQueryFnData = Array<Prisma.UserBudgetPreferenceGetPayload<TArgs>>, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceFindManyArgs>, options?: Omit<UseSuspenseInfiniteQueryOptions<TQueryFnData, TError, InfiniteData<TData>>, 'queryKey' | 'initialPageParam'>) {
    options = options ?? { getNextPageParam: () => null };
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseInfiniteModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/findMany`, args, options, fetch);
}

export function useFindUniqueUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceFindUniqueArgs, TQueryFnData = Prisma.UserBudgetPreferenceGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceFindUniqueArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/findUnique`, args, options, fetch);
}

export function useSuspenseFindUniqueUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceFindUniqueArgs, TQueryFnData = Prisma.UserBudgetPreferenceGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceFindUniqueArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/findUnique`, args, options, fetch);
}

export function useFindFirstUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceFindFirstArgs, TQueryFnData = Prisma.UserBudgetPreferenceGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceFindFirstArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/findFirst`, args, options, fetch);
}

export function useSuspenseFindFirstUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceFindFirstArgs, TQueryFnData = Prisma.UserBudgetPreferenceGetPayload<TArgs> & { $optimistic?: boolean }, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceFindFirstArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/findFirst`, args, options, fetch);
}

export function useUpdateUserBudgetPreference(options?: Omit<(UseMutationOptions<(UserBudgetPreference | undefined), DefaultError, Prisma.UserBudgetPreferenceUpdateArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserBudgetPreferenceUpdateArgs, DefaultError, UserBudgetPreference, true>('UserBudgetPreference', 'PUT', `${endpoint}/userBudgetPreference/update`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserBudgetPreferenceUpdateArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceUpdateArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, UserBudgetPreference, Prisma.UserBudgetPreferenceGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceUpdateArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, UserBudgetPreference, Prisma.UserBudgetPreferenceGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useUpdateManyUserBudgetPreference(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.UserBudgetPreferenceUpdateManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserBudgetPreferenceUpdateManyArgs, DefaultError, Prisma.BatchPayload, false>('UserBudgetPreference', 'PUT', `${endpoint}/userBudgetPreference/updateMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserBudgetPreferenceUpdateManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceUpdateManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceUpdateManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useUpsertUserBudgetPreference(options?: Omit<(UseMutationOptions<(UserBudgetPreference | undefined), DefaultError, Prisma.UserBudgetPreferenceUpsertArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserBudgetPreferenceUpsertArgs, DefaultError, UserBudgetPreference, true>('UserBudgetPreference', 'POST', `${endpoint}/userBudgetPreference/upsert`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserBudgetPreferenceUpsertArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceUpsertArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, UserBudgetPreference, Prisma.UserBudgetPreferenceGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceUpsertArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, UserBudgetPreference, Prisma.UserBudgetPreferenceGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteUserBudgetPreference(options?: Omit<(UseMutationOptions<(UserBudgetPreference | undefined), DefaultError, Prisma.UserBudgetPreferenceDeleteArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserBudgetPreferenceDeleteArgs, DefaultError, UserBudgetPreference, true>('UserBudgetPreference', 'DELETE', `${endpoint}/userBudgetPreference/delete`, metadata, options, fetch, true)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserBudgetPreferenceDeleteArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceDeleteArgs>,
            options?: Omit<(UseMutationOptions<(CheckSelect<T, UserBudgetPreference, Prisma.UserBudgetPreferenceGetPayload<T>> | undefined), DefaultError, Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceDeleteArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as (CheckSelect<T, UserBudgetPreference, Prisma.UserBudgetPreferenceGetPayload<T>> | undefined);
        },
    };
    return mutation;
}

export function useDeleteManyUserBudgetPreference(options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.UserBudgetPreferenceDeleteManyArgs> & ExtraMutationOptions), 'mutationFn'>) {
    const { endpoint, fetch } = getHooksContext();
    const _mutation =
        useModelMutation<Prisma.UserBudgetPreferenceDeleteManyArgs, DefaultError, Prisma.BatchPayload, false>('UserBudgetPreference', 'DELETE', `${endpoint}/userBudgetPreference/deleteMany`, metadata, options, fetch, false)
        ;
    const mutation = {
        ..._mutation,
        mutateAsync: async <T extends Prisma.UserBudgetPreferenceDeleteManyArgs>(
            args: Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceDeleteManyArgs>,
            options?: Omit<(UseMutationOptions<Prisma.BatchPayload, DefaultError, Prisma.SelectSubset<T, Prisma.UserBudgetPreferenceDeleteManyArgs>> & ExtraMutationOptions), 'mutationFn'>
        ) => {
            return (await _mutation.mutateAsync(
                args,
                options as any
            )) as Prisma.BatchPayload;
        },
    };
    return mutation;
}

export function useAggregateUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceAggregateArgs, TQueryFnData = Prisma.GetUserBudgetPreferenceAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceAggregateArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/aggregate`, args, options, fetch);
}

export function useSuspenseAggregateUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceAggregateArgs, TQueryFnData = Prisma.GetUserBudgetPreferenceAggregateType<TArgs>, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceAggregateArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/aggregate`, args, options, fetch);
}

export function useGroupByUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.UserBudgetPreferenceGroupByArgs['orderBy'] } : { orderBy?: Prisma.UserBudgetPreferenceGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.UserBudgetPreferenceGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.UserBudgetPreferenceGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.UserBudgetPreferenceGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.UserBudgetPreferenceGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.UserBudgetPreferenceGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/groupBy`, args, options, fetch);
}

export function useSuspenseGroupByUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceGroupByArgs, HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<TArgs>>, Prisma.Extends<'take', Prisma.Keys<TArgs>>>, OrderByArg extends Prisma.True extends HasSelectOrTake ? { orderBy: Prisma.UserBudgetPreferenceGroupByArgs['orderBy'] } : { orderBy?: Prisma.UserBudgetPreferenceGroupByArgs['orderBy'] }, OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<TArgs['orderBy']>>>, ByFields extends Prisma.MaybeTupleToUnion<TArgs['by']>, ByValid extends Prisma.Has<ByFields, OrderFields>, HavingFields extends Prisma.GetHavingFields<TArgs['having']>, HavingValid extends Prisma.Has<ByFields, HavingFields>, ByEmpty extends TArgs['by'] extends never[] ? Prisma.True : Prisma.False, InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
        ? never
        : P extends string
        ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
        : [
            Error,
            'Field ',
            P,
            ` in "having" needs to be provided in "by"`,
        ]
    }[HavingFields]
    : 'take' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<TArgs>
    ? 'orderBy' extends Prisma.Keys<TArgs>
    ? ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields]
    : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
        ? never
        : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
    }[OrderFields], TQueryFnData = {} extends InputErrors ?
    Array<PickEnumerable<Prisma.UserBudgetPreferenceGroupByOutputType, TArgs['by']> &
        {
            [P in ((keyof TArgs) & (keyof Prisma.UserBudgetPreferenceGroupByOutputType))]: P extends '_count'
            ? TArgs[P] extends boolean
            ? number
            : Prisma.GetScalarType<TArgs[P], Prisma.UserBudgetPreferenceGroupByOutputType[P]>
            : Prisma.GetScalarType<TArgs[P], Prisma.UserBudgetPreferenceGroupByOutputType[P]>
        }
    > : InputErrors, TData = TQueryFnData, TError = DefaultError>(args: Prisma.SelectSubset<TArgs, Prisma.SubsetIntersection<TArgs, Prisma.UserBudgetPreferenceGroupByArgs, OrderByArg> & InputErrors>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/groupBy`, args, options, fetch);
}

export function useCountUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.UserBudgetPreferenceCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceCountArgs>, options?: (Omit<UseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/count`, args, options, fetch);
}

export function useSuspenseCountUserBudgetPreference<TArgs extends Prisma.UserBudgetPreferenceCountArgs, TQueryFnData = TArgs extends { select: any; } ? TArgs['select'] extends true ? number : Prisma.GetScalarType<TArgs['select'], Prisma.UserBudgetPreferenceCountAggregateOutputType> : number, TData = TQueryFnData, TError = DefaultError>(args?: Prisma.SelectSubset<TArgs, Prisma.UserBudgetPreferenceCountArgs>, options?: (Omit<UseSuspenseQueryOptions<TQueryFnData, TError, TData>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useSuspenseModelQuery<TQueryFnData, TData, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/count`, args, options, fetch);
}
import type { BudgetAllocationStrategy } from '@prisma/client';

export function useCheckUserBudgetPreference<TError = DefaultError>(args: { operation: PolicyCrudKind; where?: { id?: string; userId?: string; strategy?: BudgetAllocationStrategy }; }, options?: (Omit<UseQueryOptions<boolean, TError, boolean>, 'queryKey'> & ExtraQueryOptions)) {
    const { endpoint, fetch } = getHooksContext();
    return useModelQuery<boolean, boolean, TError>('UserBudgetPreference', `${endpoint}/userBudgetPreference/check`, args, options, fetch);
}
