import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import TanStackQuery from '../providers/TanStackQuery';
import NextAuthSessionProvider from '../providers/SessionProvider';
import { Toaster } from 'sonner';

const lufga = localFont({
  src: [
    {
      path: './fonts/LufgaRegular.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/LufgaMedium.woff',
      weight: '500',
      style: 'medium',
    },
  ],
  variable: '--font-lufga',
});

export const metadata: Metadata = {
  title: 'Personal Finance Management System',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lufga.variable} antialiased`}>
        <TanStackQuery>
          <NextAuthSessionProvider>
            {children}
            <Toaster position="bottom-right" richColors />
          </NextAuthSessionProvider>
        </TanStackQuery>
      </body>
    </html>
  );
}
